spring.application.name=biblioteca-api
server.port=8080

# Spring Boot 4.0 renombró la propiedad de "spring.data.mongodb" a "spring.mongodb"
spring.mongodb.uri=mongodb+srv://paulasofiagonzaleszambrano_db_user:wzAk7HDowfka0wnC@biblioteca-cluster.4cqwhyj.mongodb.net/biblioteca_db?retryWrites=true&w=majority